name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          cd frontend
          yarn install
      - name: Linter
        run: |
          cd frontend
          yarn prettier --check .
      - name: Build
        run: |
          cd frontend
          yarn build